Add snapshot management
datastax/management-api-for-apache-cassandra pull request #53
Opened 2020-11-13 23:35 UTC by emerkle826

This PR adds GET, DELETE, and POST methods for retrieving, clearing and taking snapshots, respectively. This should resolve [issue #52](https://github.com/datastax/management-api-for-apache-cassandra/issues/52)

2020-11-13 23:38 UTC, emerkle826 commented
@tjake This should provide most of the same capabilities as `nodetool snapshot`, `nodetool clearsnapshot`, and `nodetool listsnapshots`

2020-11-17 17:47 UTC, emerkle826 commented
The 2 failing tests in the checks are due to tests for truncating Hints against Cassandra 4.0. I've tried to address that in a different PR [here](https://github.com/datastax/management-api-for-apache-cassandra/pull/54)

2020-11-18 01:28 UTC, tjake requested changes
Great stuff, could you rebase and fix a formatting nit? Then good to go

2020-11-18 01:28 UTC, tjake commented on management-api-server/src/test/java/com/datastax/mgmtapi/NonDestructiveOpsIntegrationTest.java
> +        Object responseObject = ReaderUtility.read(Object.class, MediaType.APPLICATION_JSON, getSnapshotResponse);
Formatting

2020-11-18 19:22 UTC, tjake approved these changes

2020-11-18 19:22 UTC, merged