Create home directory for cassandra user
datastax/management-api-for-apache-cassandra pull request #89
Opened 2021-03-01 21:20 UTC by careykevin

Create the `/home/cassandra` directory and make it writable for the
`cassandra` user.

This will allow files, including the cqlsh history, to be written for
the user without warnings.

Resolves #88

2021-03-02 16:51 UTC, emerkle826 requested changes
This looks good, but you need to make the same change to the DSE Dockerfile [here](https://github.com/datastax/management-api-for-apache-cassandra/blob/master/Dockerfile-dse-68)

2021-03-02 16:53 UTC, emerkle826 approved these changes

2021-03-03 19:01 UTC, emerkle826 commented
@careykevin Thank you for the contribution. All I need you to do now is to sign our CLA policy here:
https://cla.datastax.com/
and ping me back on this PR when you have.

2021-03-03 19:06 UTC, careykevin commented
Thanks @emerkle826 - I have signed the agreement.

2021-03-03 19:14 UTC, merged